id: IBF06BC6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:08:10+00:00'
last_modified: '2022-06-08T02:28:43.726518+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2488
  title: ས་སྐྱ་པའི་ཆོས་སྤྱོད་ཁྱེར་བདེ་ཀུན་ཚང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    357D:
      image_group_id: I1CZ2501
      title: ''
      total_pages: 321
      order: 1
      base_file: 357D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
