id: P004635
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:45:45.331367
source_metadata:
  id: bdr:W1CZ2488
  title: ས་སྐྱ་པའི་ཆོས་སྤྱོད་ཁྱེར་བདེ་ཀུན་ཚང་
  author: ''
  volumes:
    41acea02bdda4a78aba648f72c80cf4a:
      image_group_id: I1CZ2501
      title: ''
      volume_number: 1
      total_pages: 321
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
